create table algorithms (
    id int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table contacts (
    id int8 generated by default as identity,
    email varchar(255),
    phone_number varchar(255),
    primary key (id)
);

create table idea_statuses (
    id int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table ideas (
    id int8 generated by default as identity,
    name varchar(255) not null,
    text varchar(255) not null,
    author_id int8 not null,
    contact_id int8 not null,
    status_id int8, primary key (id)
);

create table roles (
    id int8 generated by default as identity,
    name varchar(255) not null,
    permission varchar(255) not null,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    role_id int8 not null
);

create table users (
    id int8 generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    patronymic varchar(255),
    username varchar(255) not null,
    algorithm_id int8 not null,
    primary key (id)
);

alter table if exists ideas add constraint UK_mlv2bxvpicoc15ymyiagnofdp unique (contact_id);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists ideas add constraint FK2ndsc14npjb3evrj8vrhmwjcv foreign key (author_id) references users;
alter table if exists ideas add constraint FKl6eo287c1l0oiry3f5b2pkw3x foreign key (contact_id) references contacts;
alter table if exists ideas add constraint FKpv6l76w0isvl7p4v9is0tmpl9 foreign key (status_id) references idea_statuses;
alter table if exists user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
alter table if exists users add constraint FKghhii4u2tjyu1wlmk8luskqw8 foreign key (algorithm_id) references algorithms;